### ISSUE TITLE
Droste effect release file

### ISSUE THREAD

**Issue by vdtoorn** [JanaSperschneider/EffectorP-3.0#3]
The EffectorP_3.0.0-beta.zip contains a weka zip file, which contains again the effectorp-3.0 zip file which in turn again has a weka zip file inside. This is where the recursion ends, but probably this is not needed.

**Comment by JanaSperschneider** [comment]
How strange... I fixed the release Zip file, please let me know if it works fine now.

Thanks for reporting!
Jana

**Comment by vdtoorn** [comment]
Thanks for fixing!
